### ISSUE TITLE
/etc/bahmni-installer/local: No such file or directory

### ISSUE THREAD

**Issue by egrueter-dev** [Bahmni/bahmni-tw-aws#5]
When running the Bhamni docker scripts found in `bahmni-tw-aws/dev_dockerFiles/`

I receive the following error: 
`/etc/bahmni-installer/local: No such file or directory`

What specific local configs do I need to make to pass this step? Is this supposed to be included in the `.sh` file?

Thanks,

**Comment by xtrasimplicity** [comment]
@angshuman, I just wanted to check whether this is still on TW's roadmap, or if it has been abandoned? It's been quite some time since anything has changed, and there's a few PRs and issues that have gone unanswered.

Is there a more up-to-date repository that we should use? I'm keen to start moving a few Bahmni installations to Docker and would prefer to avoid deviating too much from any official images. Happy to help out in any way I can, too! 

Thanks heaps!

**Comment by xtrasimplicity** [comment]
Sorry, @angshuman - I meant to ping @angshu.

**Comment by Luxas98** [comment]
Hi fellas, I wanted to try Bahmi setup but it seems this error is still blocking the docker setup, any update on it?

**Comment by xtrasimplicity** [comment]
@luxas98 I suspect this repo may be pretty much abandoned. Many users have created their own unofficial docker images:

Médecins sans frontieres: https://github.com/MSF-OCB/bahmni-docker
Bahmni (official - but possibly unstable, I haven't used them before): https://hub.docker.com/u/bahmni

If you want to trial bahmni EndTB, I built an image for v2.0.3. It isn't really production-ready yet, as it hasn't been battle tested, but it should work as a proof of concept: https://hub.docker.com/r/xtrasimplicity/bahmni-endtb-docker

Hope this helps!
